// <auto-generated />
namespace GdzieIzKim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _6krok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6krok));
        
        string IMigrationMetadata.Id
        {
            get { return "201801251716542_6krok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
