// <auto-generated />
namespace GdzieIzKim.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _4krok : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4krok));
        
        string IMigrationMetadata.Id
        {
            get { return "201801241951001_4krok"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
